### ISSUE TITLE
identityref not correctly validated

### ISSUE THREAD

**Issue by gusmb** [CZ-NIC/yangson#102]
I have a leaf in a yang module (mymodule.yang) referencing an identity in another module:

leaf test-identity {
      type identityref {
        base referenced:myidentity;
      }
  }

The reference module defines the list of identities (module referenced.yang):

identity myidentity {
    description "base identity";
  }

  // Test identities
  // ---------------

  identity ident1 {
    base myidentity ;
  }

  identity ident2  {
    base myidentity ;
  }

When I initialize the data instance, the value gets cooked as follows:

"test-identity": "referenced:ident1",

However when I validate I get an error:
YangTypeError: {/mymodule:configuration/test-identity} invalid-type: not derived from referenced:myidentity

**Comment by llhotka** [comment]
I completed the two modules (and YANG library data) based on your fragments, and everything seems to work:
```
(yangson) $ cat mymodule.yang
module mymodule {

  namespace "http://example.com/mymodule";

  prefix mm;

  import referenced {
    prefix rm;
  }

  leaf test-identity {
    type identityref {
      base rm:myidentity;
    }
  }
}
(yangson) $ cat referenced.yang 
module referenced {

  namespace "http://example.com/referenced";

  prefix rm;

  identity myidentity {
    description
      "base identity";
  }

  identity ident1 {
    base myidentity;
  }

  identity ident2 {
    base myidentity;
  }
}
(yangson) $ cat yang-library-data.json 
{
  "ietf-yang-library:modules-state": {
    "module-set-id": "",
    "module": [
      {
        "name": "referenced",
        "revision": "",
        "namespace": "http://example.com/referenced",
        "conformance-type": "implement"
      },
      {
        "name": "mymodule",
        "revision": "",
        "namespace": "http://example.com/mymodule",
        "conformance-type": "implement"
      }
    ]
  }
}
(yangson) $ cat example-data.json 
{
  "mymodule:test-identity": "referenced:ident1"
}
(yangson) $ yangson -v example-data.json yang-library-data.json 
(yangson) $
```
Please check what's different in your case. My guess is that `referenced` module has
```
"conformance-type": "import"
```
in your YANG library. It has to be `implement`, see sec. [9.10.2](https://www.rfc-editor.org/rfc/rfc7950.html#section-9.10.2) in RFC 7950 (last sentence).

**Comment by gusmb** [comment]
The difference in my case is that I don't specify the module name for the identity in the instance data:
```
$ cat example-data.json 
{
  "mymodule:configuration": {
      test-identity": "ident1"
  }
}
```
Since mymodule already referenced the identity in the the referenced module, there is no need to indicate it in the instance data

```
leaf test-identity {
    type identityref {
      base rm:myidentity;
    }
  }
```

I would expect that the above instance data would also validate, but instead it throws error:

```
YangTypeError: {/mymodule:configuration/test-identity} invalid-type: not derived from referenced:myidentity
```

Also noticed that if I use this format, YANGSON adds a prefix in the instance value wrongly:

```
print(instance['mymodule:configuration']['test-identity'].raw_value())
mymodule:ident1
```

and looking at value:
```
print(instance['mymodule:configuration']['test-identity'].value)
('ident1','mymodule')
```

If I indicate the referenced module explicitely in raw_value in my instance data, then the cooked version does not get modified:

```
print(instance['mymodule:configuration']['test-identity'].raw_value())
referenced:ident1
```

And the value shows the correct tuple:
```
print(instance['mymodule:configuration']['test-identity'].value)
('ident1','referenced')
```

So in my view the problem is the "transformation" that Yangson does to the raw value when I don't specify the identity source module in the value. While it is necessary to indicate the module for the leaf, it should not be the case for the leaf value.

The correct behavior would be:

```
$ cat example-data.json 
{
  "mymodule:configuration": {
      test-identity": "ident1"
  }
}
```

when create the instance in yangson from raw input:

- Cook the value for ident1 as follows, base purely on the information from the data model, which is already there:

```
print(instance['mymodule:configuration']['test-identity'].value)
('ident1','referenced')
```

instead of  `('ident1','mymodule')`:

**Comment by llhotka** [comment]
> The difference in my case is that I don't specify the module name for the identity in the instance data:
> 
> ```
> $ cat example-data.json 
> {
>   "mymodule:configuration": {
>       test-identity": "ident1"
>   }
> }
> ```

This is not correct, see sec. [6.8](https://tools.ietf.org/html/rfc7951#section-6.8) in RFC 7951:

*If the identity is defined in a module other than the leaf node containing the identityref value, the namespace-qualified form (Section 4) MUST be used.*

**Comment by llhotka** [comment]
Note that you can also modify `mymodule` like this:
```
module mymodule {

  namespace "http://example.com/mymodule";

  prefix mm;

  import referenced {
    prefix rm;
  }

  identity ident1 {
    base rm:myidentity;
  }

  leaf test-identity {
    type identityref {
      base rm:myidentity;
    }
  }
}
```
Then the instance
```
 test-identity": "ident1"
```
refers to the identity `ident1` defined in `mymodule`. The fact that the base identity is defined in `referenced` doesn't mean that all identities derived from it have to be found there.

**Comment by gusmb** [comment]
This works. Thanks for the hint. Closing as this is not a bug
