### ISSUE TITLE
"data-not-unique" errors do not give an error message

### ISSUE THREAD

**Issue by christian-herber** [CZ-NIC/yangson#104]
When lists have entries that do not satisfy the uniqueness condition, a semantic error is raised, but no message is provided when raising the error.
In particular for a list, a non-uniqueness is hard to track down when the list hast potentially 1000s of entries.
So here, I think it would be great to at least provide the indeces of list entries which are non-unique.

**Comment by llhotka** [comment]
The error message now shows the index of the second entry that violates `unique`.
