### ISSUE TITLE
Exception when converting a 'list-key-missing' error to string

### ISSUE THREAD

**Issue by christian-herber** [CZ-NIC/yangson#105]
Printing errors works find most of the time. But there is at least one case where the string conversion gives an exception itself.
Exception is happening due to no instance route being able to be determined. This seems logical, but the behavior should be a bit more graceful. It is clear which list entry has a missing index and that should be reported.

The error stack looks as follows

  File "...\yangson\exceptions.py", line 413, in __str__
    return f"{{{self.instance.instance_route()}}} {self.tag}{msg}"
  File "...\yangson\instance.py", line 233, in instance_route
    res.insert(0, inst._instance_route_entry())
  File "...\yangson\instance.py", line 955, in _instance_route_entry
    kdict[(k[0], None)] = str(self[k[0]])
  File "...\yangson\instance.py", line 197, in __getitem__
    return self._member(key)
  File "...\yangson\instance.py", line 578, in _member
    raise NonexistentInstance(self, f"member '{name}'") from None
yangson.exceptions.NonexistentInstance: <exception str() failed>

**Comment by llhotka** [comment]
Fixed in f91bce7. Thanks for reporting.
