### ISSUE TITLE
Problem with 'must' statement referring list entry

### ISSUE THREAD

**Issue by michael-stemmler** [CZ-NIC/yangson#17]
I'm trying to work with a model containing a 'must' statement which checks the equality of a leaf within a list entry.

The example-statement looks like:
<pre>
must "/mod:container1/mod:list-a[mod:name=.]/mod:identifier=../identifier"
</pre>

Example yang-file:
https://github.com/michael-stemmler/yangson-test/blob/master/yangmodule/must-statement/example-module.yang#L38

Using this model with this [example-data](https://github.com/michael-stemmler/yangson-test/blob/master/test/test_must_statement.py#L15) gives an SemanticError exception
<pre>
def _check_must(self, inst: "InstanceNode") -> None:
        for m in self.must:
            if not m.expression.evaluate(inst):
                raise SemanticError(inst.json_pointer(), m.error_tag,
>                                   m.error_message)
E               yangson.exceptions.SemanticError: [/example-module:container2/list-b/0/list-a-name] must-violation

../../../../venv/testyangson/lib/python3.6/site-packages/yangson/schemanode.py:783: SemanticError
</pre>

When changing the statement to
<pre>
must "/mod:container1/mod:list-a[.]/mod:identifier=../identifier"
</pre>
my test runs successful.

But I think the first case is also a valid expression.

Thanks

**Comment by llhotka** [comment]
The correct expression is
```
must "/mod:container1/mod:list-a[mod:name=current()]/mod:identifier=../identifier";
```
In your original expression, the dot (`.`) selects the node `mod:list-a`, not `list-a-name`.

Your second expression doesn't raise a validation error, but it also doesn't check that the name of `list-a` entry is the same as `list-a-name`. The `must` constraint in this case is satisfied if there is *any* `list-a` entry whose `mod:identifier` is the same as `../identifier`.

In fact, the test `[.]` is totally redundant.

**Comment by michael-stemmler** [comment]
@llhotka Thank you very much for the clarification :+1:
