### ISSUE TITLE
honor `regexp-posix` in openconfig models

### ISSUE THREAD

**Issue by dbarrosop** [CZ-NIC/yangson#23]
This is related to #22. Looks like they added already an extension to flag when they use POSIX regexes:

https://github.com/openconfig/public/blob/master/release/models/openconfig-extensions.yang#L100

Should yangson honor that?

**Comment by llhotka** [comment]
Yes, they use the extension `regexp-posix` for this purpose. I will have a look.

**Comment by llhotka** [comment]
POSIX defines two flavours of regular expressions, Basic (BRE) and Extended (ERE). The definition of `regexp-posix` extension doesn't state which of them is supported in OpenConfig. Any idea?

**Comment by dbarrosop** [comment]
Just referenced this issue on another issue of them asking them if they can answer this. Thanks a lot for looking into this, I am out next week on vacations but if you need anything don't hesitate to let me know, happy to help on anything you need once back.
