### ISSUE TITLE
update `__str__` representation for yangson.xpathast.LocationPath

### ISSUE THREAD

**Issue by kwatsen** [CZ-NIC/yangson#29]
The following captures an email exchange that occurred in June.

Kent writes: 

> When iterating over a DataModel, there are TerminalNodes of type LeafrefType.  I wish to get the leafrefs original XPath expression, as it was in the YANG module (or close to it).  The "path" attribute returns type LocationPath, which converts to a string as below, but is there anyway to get a "flattened" path expression?
> 
> LocationPath
>   LocationPath
>     LocationPath
>       LocationPath
>         LocationPath
>           LocationPath
>             Root
>             Step (child ('keystore', 'ex-module'))
>           Step (child ('asymmetric-keys', 'ex-module'))
>         Step (child ('asymmetric-key', 'ex-module'))
>       Step (child ('certificates', 'ex-module'))
>     Step (child ('certificate', 'ex-module'))
>   Step (child ('name', 'ex-module'))

Lada writes: 

> Do you need just a linear representation of the leafref path, or the exact argument of the "path" statement? In the latter case, it would be possible to store the argument with each leafref type during parsing, but then of course the namespace prefix bindings would be lost.

Kent writes:

>  I’m thinking that something like a data_path would be the best I could hope for.  So, not exactly the original leafref path value, as the prefix is converted to the module’s name. 

Lada writes: 

> OK, this should be possible. In fact, this may be a better choice as the output of the __str__ method for XPath Expression..

Update: I may have meant "schema_path" (not "data_path") in my last comment above.

**Comment by llhotka** [comment]
@kwatsen, what to do with namespaces? Instances of the `Expr` class do no have the XPath context with which they were parsed. The simplest solution would be to print each `Step` with the module name, but this could lead to rather long strings.

**Comment by kwatsen** [comment]
Module names is good.  Used in other places too, right?

To keep the length down, could the prefix be suppressed when the node’s module name is the same as its parent?

**Comment by llhotka** [comment]
The latter has two drawbacks:
- it doesn't follow XPath rules
- it is not easily done because the sequence of steps results from a recursive/inorder AST traversal - and each `Step` has has a `LocationPath` as its parent.

Another option might be to also record, for  each `Step`, the actual prefix that was used for it in the input expression. A potential drawback could be that the prefix has to be specified if the AST is constructed directly, i.e. not parsed fro a serialized form. I don't know about any use cases though.

**Comment by llhotka** [comment]
I already have a working version with module names everywhere, so perhaps we can start with that.

**Comment by llhotka** [comment]
@kwatsen please test.

**Comment by llhotka** [comment]
@kwatsen a bugfix of XPath evaluation had a side effect of adding explicit namespace (module name) to every XPath `Step` in the expression's string representation. It makes them of course considerably longer but I hope it is not a big problem - ocassionally it may even be useful.
