### ISSUE TITLE
Using an "empty" value in a leaf of the YANG tree throws an error

### ISSUE THREAD

**Issue by OfWolfAndMan** [CZ-NIC/yangson#31]
Error received:

yangson.exceptions.RawTypeError: [/ietf-snmp:snmp/enable/enable-choice/traps/syslog] expected empty value.

YANG structure:
```
// snmp-server enable traps
container traps {
	description
	"Enable SNMP Traps";
	presence true;
		leaf syslog {
		  description
		  "Enable SNMP syslog traps";
	           type empty;
		}
}
```
I had to change to a "boolean" type to work. The "empty" data type is defined as a boolean in YANG that is implicitly set to False unless explicitly specified otherwise

**Comment by llhotka** [comment]
What was the JSON instance that you used? See [RFC 7951](https://tools.ietf.org/html/rfc7951#section-6.9).

**Comment by OfWolfAndMan** [comment]
It should've looked something like this:
```
snmp {
    enable{
        traps {
            syslog : true
        }
    }
}
```

**Comment by llhotka** [comment]
The corrent JSON representation is
```
syslog: [null]
```
see [Section 6.9](https://tools.ietf.org/html/rfc7951#section-6.9) in RFC 7951.

(Sorry it took me so long.)
