### ISSUE TITLE
Using "pattern '\*'" under a string type throws an error

### ISSUE THREAD

**Issue by OfWolfAndMan** [CZ-NIC/yangson#32]
Error thrown: yangson.exceptions.InvalidArgument: \* (Using the model ietf-netconf-acm@2012-02-22.yang).
```
  typedef matchall-string-type {
    type string {
      pattern "\*"
    }
    description
      "The string containing a single asterisk '*' is used
       to conceptually represent all possible values
       for the particular leaf using this data type.";
  }
```
Had to remove the pattern to get the output to render properly.

**Comment by llhotka** [comment]
This is a known problem in RFC 6536, see [erratum](https://www.rfc-editor.org/errata/eid3862). So either patch the ietf-netconf-acm@2012-02-22.yang module, or use the revision from [RFC 8341](https://tools.ietf.org/html/rfc8341).
