### ISSUE TITLE
Missing default for types in groupings

### ISSUE THREAD

**Issue by iwanb** [CZ-NIC/yangson#35]
If a type has a default in a grouping, it seems that yangson does not pick it up.

See the last commit for a testcase:
https://github.com/iwanb/yangson/tree/test_grouping

**Comment by llhotka** [comment]
This is not valid YANG:
```
leaf leafGroup {
  type uint8 {
    default "10";
  }
}
```
What you can do is either
```
leaf leafGroup {
  type uint8;
  default "10";
}
```
or define the default for a *derived* type:
```
typedef myuint8 {
  type uint8;
  default "10";
}  
leaf leafGroup {
  type myuint8;
}
```

**Comment by iwanb** [comment]
Ah indeed, sorry, I just kept on wondering why my default was not there but of course it's on the leaf...
