### ISSUE TITLE
Multiline descriptions are parsed incorrectly

### ISSUE THREAD

**Issue by pdavies** [CZ-NIC/yangson#38]
If I have a statement with a multi-line description:

```
    leaf someleaf {
      type string;
      description
        "This is a description that just keeps on going on
         and on
         and on.";
    }
```

Then yangson will wrongly preserve all the whitespace:

```
>>> someleaf.schema_node.description
'This is a description that just keeps on going on\n         and on\n         and on.'
```

[RFC 7950 6.1.3](https://tools.ietf.org/html/rfc7950#section-6.1.3) says:

> If a double-quoted string contains a line break followed by space or
   tab characters that are used to indent the text according to the
   layout in the YANG file, this leading whitespace is stripped from the
   string, up to and including the column of the starting double quote
   character, or to the first non-whitespace character, whichever occurs
   first.

So I would expect the correct interpretation of the string to be `'This is a description that just keeps on going on\nand on\nand on.'`

Presumably this applies to string parsing in general, not just to descriptions. I haven't checked.

**Comment by llhotka** [comment]
This was omitted intentionally. It is a fancy feature that complicates the parser and moreover, makes the parsing results brittle. If a description is used outside the YANG module, then it can either be used as it is (e.g. in HTML), or needs to be processed anyway even if the YANG rule cited above is followed.
