### ISSUE TITLE
Timestamp changes independent from config/non-config state

### ISSUE THREAD

**Issue by HRogge** [CZ-NIC/yangson#48]
Is the timestamp feature of the Instance objects meant to track the timestamp referred in RFC8040?

Section 3.5.1 states:
`This timestamp is only affected by configuration data resources and MUST NOT be updated for changes to non-configuration data.`

(edit: removed suggested solution, as always it is a little bit more complicated)

**Comment by llhotka** [comment]
Yes, it was meant as RFC 8040 timestamps, but only for container-like objects, i.e. leaf instances and leaf-list entries don't have them.

It is true that they are also kept for state data.

**Comment by HRogge** [comment]
For container-object sounds fine, because they are the only ones that form the tree... I will try to experiment with a few solutions, my first guess was to modify the upwards-copy of the timestamp in the up() function depending on "config or not config"... but there are a few cases when this is not enough.

**Comment by llhotka** [comment]
I suspect that the handling of timestamps isn't always consistent.
