### ISSUE TITLE
Skip leafref in validation

### ISSUE THREAD

**Issue by dmfigol** [CZ-NIC/yangson#52]
I have been trying to apply **yangson** to some models I have been working with, in particular Cisco IOS-XE models and OpenConfig. Openconfig models leverage many **leafref**, mostly referencing openconfig-interfaces and it seems that for yangson validation to succeed, the data always need to have those trees referenced in leafref.  
I have been wondering if it is possible to skip this particular validation as it becomes hard to provide this additional supporting data,

**Comment by llhotka** [comment]
If the leafref definition has `require-instance` set to `true` (which is the default), then sematic validity requires the referenced leaf to be present. So one option is to set temporarily `require-instance` to `false` for the leafref.

What could alo help is to restrict validation scope to `syntax`, which can be done e.g. with
```
yangson -s syntax ...
```
or by setting the `scope` archument of the `validate` method, see
https://yangson.labs.nic.cz/instance.html#yangson.instance.InstanceNode.validate
