### ISSUE TITLE
Leafref datatype should implement from_yang

### ISSUE THREAD

**Issue by iwanb** [CZ-NIC/yangson#57]
Since commit 1c60783a4db8f8153a833707b69dc8cbe64ba88e doing `leafreftype.from_yang("1")` on an integer leafref will return None because it will use the default implementation which calls `from_raw`, which only accepts integers.

I guess `parse_value` should also be implemented.

**Comment by llhotka** [comment]
Fixed in 0f4657ecce41b526f3dee0bd15b0bc580834bcb9
