### ISSUE TITLE
Parsing individual YANG models with yangson?

### ISSUE THREAD

**Issue by remingtonc** [CZ-NIC/yangson#6]
Is it possible to parse individual YANG models with the yangson library? For instance - https://github.com/YangModels/yang/blob/master/standard/ietf/RFC/ietf-ip%402014-06-16.yang

Ideally, I am looking to extract all YANG XPaths available from this YANG model, along with some attributes such as their data type, description, etc. Any tips?

**Comment by llhotka** [comment]
This is not possible, yangson has to process a complete data model. You can process *ietf-ip* together with *ietf-interfaces*, but without the latter the augments contained in *ietf-ip* don't have their target nodes.

Perhaps you can use [pyang](https://github.com/mbj4668/pyang) instead, which is more module-oriented.
