### ISSUE TITLE
find Statement from SchemaNode / extensions

### ISSUE THREAD

**Issue by dimbleby** [CZ-NIC/yangson#60]
Suppose I have a `DataModel`, and an instance (created via `from_raw()`).

As I traverse the instance, is there a way for me to find the `Statement` corresponding to a `SchemaNode`?

This may be an XY question, so here's my use case - perhaps I'm missing some altogether better way.

I want to define an extension:

```yang
 extension sensitive {
 description
   "A new YANG keyword used to indicate that a node should be considered sensitive.";
 }
```

and then in my model I want to mark some nodes as sensitive eg

```yang
    leaf secret {
      type string;
      my-prefix:sensitive;
    }
```

And now as I traverse my instance, I want to be able to tell whether I have a sensitive node or not.

Experiment shows that yangson is happy to treat my extension as valid and turn it into a `Statement`, but I'm struggling to access that information when I need it.

What I have made work is monkey-patching the `SchemaNode`, something like this:

```python
def my_sensitive_stmt(self, stmt, sctx):
    self.sensitive = True


SchemaNode._my_sensitive_stmt = my_sensitive_stmt
SchemaNode._stmt_callback["my-prefix:sensitive"] = "_my_sensitive_stmt"
```

Now the node gets a `sensitive` attribute, if it is marked sensitive in the schema.

Am I missing an easier way to do this?  If not: would yangson have any interest in exposing an API that allowed me to avoid this monkey-patching?

**Comment by llhotka** [comment]
There is currently no connection from a schema node back to its definition in a YANG module.

Your approach is basically OK, alternatively you can fork the project and implement it directly in the `SchemaNode` class.
