### ISSUE TITLE
Deviations in yang library not supported

### ISSUE THREAD

**Issue by christian-herber** [CZ-NIC/yangson#64]
From what i can tell, i do not see support for deviation statement in the parsing done in SchemaData._from_yang_library()
First off, is my observation correct? Is there any intention to add this?
In practice, deviations are widely used and an important aspect in getting an accurate model of the device.

**Comment by llhotka** [comment]
This is correct, deviations are not supported. I have currently no planes to implement them.

**Comment by llhotka** [comment]
Implemented in version 1.4.4.
