### ISSUE TITLE
to_xml() on RootNode doesn't include top-level "content-data" element

### ISSUE THREAD

**Issue by kwatsen** [CZ-NIC/yangson#69]
Adding the following to tests/test_model.py:
```
import xml.etree.ElementTree as ET

def test_xml(data_model):
    data_minus_anydata = {
        "test:llistB": ["::1", "127.0.0.1"],
        "test:leafX": 53531,
        "test:contA": {
            "leafB": 9,
            "listA": [{
                "leafE": "C0FFEE",
                "leafF": True,
                "contD": {
                    "leafG": "foo1-bar",
                    "contE": {
                        "leafJ": [None],
                        "leafP": 10
                    }
                }
            },
            {   
                "leafE": "ABBA",
                "leafW": 9,
                 "leafF": False
            }],
            "testb:leafR": "C0FFEE",
            "testb:leafT": "test:CC-BY",
            "testb:leafV": 99,
            "testb:leafN": "hi!"
        },
        "test:contT": {
            "bits": "dos cuatro",
            "decimal64": "4.50",
            "enumeration": "Hearts"
        }
    }
    inst = data_model.from_raw(data_minus_anydata)
    print("type(inst) = " + str(type(inst)))

    # convert InstanceValue to an XML-encoded string
    xml_obj = inst.to_xml()
    xml_text = ET.tostring(xml_obj).decode("utf-8")
    print("xml_text = " + xml_text)
```

Produces this output:
```
type(inst) = <class 'yangson.instance.RootNode'>
xml_text = <llistB xmlns="http://example.com/test">::1</llistB>
```

Why isn't the [code here](https://github.com/CZ-NIC/yangson/pull/51/commits/56d7447c46a5c4cfcdd8dfaf65c9a01f9c8898e3), which was [discussed here](https://github.com/CZ-NIC/yangson/pull/51#issuecomment-631475124), working?

**Comment by kwatsen** [comment]
PS: I didn't get to test it, but the next few lines of code looked like this:
```
    # convert to XML-encoded string back to an InstanceValue
    xml_obj = ET.fromstring(xml_text)
    inst = data_model.from_xml(xml_obj, True)

    # ensure raw value is same
    rv = inst.raw_value()
    assert(rv == data_minus_anydata)
```

**Comment by kwatsen** [comment]
Related, but the `InputNode` and `OutputNode` (and, I imagine, also `NotificationNode`) are also missing namespace prefixes:

```
from yangson.instance import RootNode

def test_xml_rpc(data_model):
    input_obj = {
        "testb:input" : {
            "leafK" : 123
        }
    }
    rpc_sn = data_model.get_schema_node("/testb:rpcA")
    print("\n")
    input_inst_val = rpc_sn.from_raw(input_obj, allow_nodata=True)
    input_inst= RootNode(input_inst_val, rpc_sn, data_model.schema_data, input_inst_val.timestamp)
    input_xml_obj = input_inst.to_xml()
    input_xml = ET.tostring(input_xml_obj).decode("utf-8")
    print("input_xml = " + input_xml)
    input_raw = input_inst.raw_value()
    print("input_raw = " + str(input_raw))
    assert(input_raw == input_obj)
```

Produces this output (note that the "raw" is correctly prefixed):
```
input_xml = <input><leafK>123</leafK></input>
input_raw = {'testb:input': {'leafK': 123}}
```

But, in this case, we do NOT want to create a `content-data` element, but rather just add the "testb" namespace prefix into the top-level <input> and <output> elements.


PS: I'd show the "output", but there is a separate issue for it (see #70)

**Comment by HRogge** [comment]
One issue I should mention is that XML has one fundamental structural difference to JSON... a named root node! You cannot convert a JSON representation starting with a dictionary with multiple keys to XML without adding a root node in front of it. 

It is one of the difficulties I had to work around when creating the XML code.

**Comment by llhotka** [comment]
One solution that could be implemented for both JSON and XML might be to introduce an auxiliary container (such as `yangson:data`) and expect instance data to be always wrapped in it. This is something the `input` node provides for RPC input.

It is IMO a flaw in RESTCONF (or YANG?) that it doesn't define such a resource for universal use.

**Comment by HRogge** [comment]
I put the user YANG tree below the "Unified Data Model tree" (ietf-restconf module) in my server code, which gives me (among other things) the data node.

The main issue with adding this to yangson is that it might break everyones code... because at the moment (at least when working with JSON) a dictionary with multiple keys on the root layer is fine... but its not possible to represent this in XML.

**Comment by llhotka** [comment]
Yes, unfortunately. When I started with Yanson, I didn't plan to support XML.

One option might be to silently accept either nothing (current situation) or that new wrapper for JSON, and require the wrapper for XML.

**Comment by HRogge** [comment]
You can see the issue even in my current XML code in "from_xml()" in schema_node.py line 481... I had to add the "isroot" variable to make a switch between the two necessary behaviors.
(I have to admit I am not that deep inside my code anymore after 6 months "break")

**Comment by kwatsen** [comment]
> One issue I should mention is that XML has one fundamental structural difference to JSON... <snip/>

I’m aware, this is why I wrote “Why isn't the *code here*, which was *discussed here*, working?” above (where the now-bold items were hyperlinks)

AFAICT, the solution has already been discussed, and the fix committed, but it’s not working?

I’m unsure if an XML, YANG, or RC bug.  But the same issue is arising in my list-pagination draft, whereby the sequence of list or lead-list entries must be wrapped in order to have a legal XML document.  Personally, I would’ve been okay returning an illegal XML document, being a sequence of legal XML documents, much like a multi-part PEM file. 

It’s too bad rfc8040 doesn’t include a GET example for a datastore containing more than one element, but I think that it’s this “data” element (defined in ietf-restconf.yang) is intended to wrap everything, as shown for the PATCH examples in B.2.3 and B.2.4. 

But I think we need to separate how Yangson processes instance documents and what’s needed for RESTCONF.  Yangson just needs to be internally consistent with how it treats multi-part XML “documents”...it’s not a JSON-thing...we just need something for XML. Let the app-logic (e.g., jetconf), handle replacing RESTCONF-envelope with what’s needed for Yangson. 

We just need to_xml() and from_xml() to be consistent when handling a RootNode (albeit, not when RootNode is used for InputNode or OutputNode).   (again, I’m a fan of an illegal multipart XML file...FWIW, this is what ‘yanglint’ uses...)

**Comment by kwatsen** [comment]
Continuing my previous comment, seems that the logic would be:

1. when importing an XML “datastore”, “list”, or “leaf-list”

   - app deserializes XML string into ET object 
   - app modifies ET object top-level node
   - app passes modified ET object into from_xml()

2) when exporting an XML “datastore”, “list”, or “leaf-list”

   - app uses to_xml() to output ET object
   - app modifies ET object top-level node
   - app serializes ET object to XML string

Alternatively, for (1), Yangson could silently discard any top-level node found and, for (2), user could pass to_xml() params for the top-level node element and namespace to use (on this last point, I recall it being discussed before). 

PS: by list/leaf-list, I recall Yangson supports direct ArrayNode manipulation, which would be exercised by my budding list-pagination draft...

**Comment by kwatsen** [comment]
Henning,

Can you please respond?   Please say if no longer interested or able to be involved, so we can make decisions more quickly.

Can you first say why your code [linked here](https://github.com/CZ-NIC/yangson/pull/51/commits/56d7447c46a5c4cfcdd8dfaf65c9a01f9c8898e3), which was [discussed here](https://github.com/CZ-NIC/yangson/pull/51#issuecomment-631475124), isn't working?   The commit was to solve this very issue, right?

Also, per my last message, it seems that your code (linked in the previous paragraph) fully implements "Option 2" - right?  At least it seems that from_xml(allow_nodata=True) strips off whatever top-level node is present, while the to_xml() will use default tag/urn values only if app-supplied values are not passed.

**Comment by HRogge** [comment]
Sorry, first day of my Winter vacation and Christmas planning stress is hitting hard... I come back to your post in the next few days, okay?

**Comment by kwatsen** [comment]
I made a few patches to Yangson and got a little more working.  I’ll try sharing a PR tomorrow. 

K.

**Comment by kwatsen** [comment]
I made a couple checkin's today:

1. A standalone PR (#71) that simply improves the readability of Yangson (not XML-related)
     - I plan to use this PR as the basis for all my XML-work, as otherwise I find Yangson unreasonably hard to work with
     - I hope Lada will merge, but it assumes he's okay with Python >= 3.7...

2. The beginning of an attempt to improve the XML-support provided by Henning's PR (e0674dbdd3f2f89e852e4b0175e9843f091fb715)
     - Currently just shows "config" working, but hope to extend for RPC/Action/Notification
          - so far my attempts to get RPC working have failed, but I'll give it another day but crying mercy
               - Lada, I'm desperate for a response to that email regarding proper usage of "RootNode"...
     - Due to issues in the XML-code, the pytest must use "xml-safe" versions of the data-model and data.
          - Henning, you may want to dig in here, to remove these restrictions

**Comment by kwatsen** [comment]
BTW, this Issue (as it's defined in the OP) could be closed if/when a PR containing 5430aac is merged...

I just pushed another commit (68767ebfb383eb8c7a3aa35126a41286f92aa81c) to my [xml-improved fork](/kwatsen/yangson/tree/xml-improved).  This commit adds a pytest called `test_xml_rpc()` that converts RPC inputs and outputs to/from XML and raw values.

This was incredibly difficult to do without any working examples, documentation, or responsive collaborators.   Honestly, it was partially luck landing on a specific combination that worked.

I'm unhappy with the `allow_nodata` and `isroot` parameters.  Henning, can you please consider if possible to let the code determine the right thing to do from where it is in the schema tree?

Also, be advised the ET trees are being constructed differently:
  - to_xml() creates an ET that puts the namespace into an `attrib` variable
  - ET.parsestring() creates an ET that mangles the namespace into the `tag` and uses prefixes (no default `xmlns`)

It sorta works itself out, as the right ET is given the clients and Yangson happens to consume the mangled ET (from `parsestring()`), but asymmetries bug me...

I wonder if using `lxml` instead of `ET` would help...

**Comment by HRogge** [comment]
The issue with ET and namespace attributes is why I created the xmlparser class (to access other namespaces than the used one)... theoretically we could also fix the "ET namespace to tag-name" in a similar way.

At the moment the xml-improved-fork (to be exact the merge with submodels) breaks my server code (ALL testcases fail, so it is something very generic), I am looking into the issue.

**Comment by HRogge** [comment]
Okay, I had another mistake in the merge (had to do most of it by hand, GIT couldn't handle it for some reason)... my servers testcases now all show "ok" when based on your xml-improved code.

**Comment by llhotka** [comment]
> I wonder if using `lxml` instead of `ET` would help...

I prefer ET, as it is part of Python standard library. The XML code requires cleanup and consolidation, which includes adding tests and documentation (both docstrings and Sphinx stuff).

**Comment by kwatsen** [comment]
Closing this issue since Pull #81  has been merged.
