### ISSUE TITLE
Yangson 1.3.60 on Python 3.6 - import failure

### ISSUE THREAD

**Issue by murrayrogers** [CZ-NIC/yangson#74]
Hi!

Per the respective readmes, 1.3.59 requires Python 3.5+, while 1.3.60 requires 3.7+.  At face value that's OK, but with `pip install` on Python 3.6 of "yangson<2.0,>=1.3" that causes runtime failures, as 1.3.60 gets installed and hits an `import` error:

```
File "/usr/local/lib/python3.6/site-packages/yangson/__init__.py", line 1, in <module>
    from .datamodel import DataModel    # NOQA
  File "/usr/local/lib/python3.6/site-packages/yangson/datamodel.py", line 25
    from __future__ import annotations
```

It feels like either (or both):
 - this should be a breaking change in semver (so 2.0.0 not 1.3.60)
 - potentially `.python-version` should be updated to say 3.7.0 not 3.5.1 (though I'm not instantly sure if e.g. `pip` uses that to constrain versions)

Maybe too late to take the former route, unless a corrective 1.3.61 is produced??  I guess the workaround is to cap pip explicitly at 1.3.59 in this environment?

Thanks!

**Comment by llhotka** [comment]
This is now fixed in 1.3.61, pip will require Python 2.7 or later. Thanks for reporting.
