### ISSUE TITLE
BinaryType decode/encode doesn't work on some values

### ISSUE THREAD

**Issue by kwatsen** [CZ-NIC/yangson#75]
Adding the following to tests/test-model.py
```
def test_binary(data_model):
    rv = {
            "test:contT": {
                "binary": 'base64encodedvalue=='
            }
         }
    root = data_model.from_raw(rv)
    sn = data_model.get_schema_node("/")
    instval = sn.from_raw(rv, allow_nodata=True)
    inst = RootNode(instval, sn, data_model.schema_data, instval.timestamp)
    assert(inst.raw_value() == rv)
```

And running:
```
pytest -sxvvk test_binary
```

Produces this output:
```
>       assert(inst.raw_value() == rv)                                                                                 
E       AssertionError: assert {'test:contT': {'binary': 'base64encodedvaluQ=='}} == {'test:contT': {'binary': 'base64encodedvalue=='}}                                           
E         Differing items:
E         {'test:contT': {'binary': 'base64encodedvaluQ=='}} != {'test:contT': {'binary': 'base64encodedvalue=='}}
E         Full diff:
E         - {'test:contT': {'binary': 'base64encodedvalue=='}}
E         ?                                             ^
E         + {'test:contT': {'binary': 'base64encodedvaluQ=='}}
E         ?                                             ^
```

**Comment by kwatsen** [comment]
The BinaryType uses the `base64` module's `b64decode()` and `b64encode()` routines that, in turn, use the `binascii` module's `b2a_base64()` and `a2b_base64()` routines.

The bug also manifests via the `binascii` routines.  A bug has been submitted against Python here: [binascii doesn't work on some base64](https://bugs.python.org/issue42628)

This PR is dependent on the resolution to the underlying Python issue.

**Comment by kwatsen** [comment]
@llhotka @HRogge 

Can one of you verify this bug is real?  Either via the pytest in the OP or via the `binascii` PR?

This was working for me before, so now I'm wondering if it might have something to do with, e.g., the version of `OpenSSL` I have installed...

Thanks,
Kent

**Comment by llhotka** [comment]
Yes, that's how it works in Python 3.9:
```
>>> from base64 import b64encode, b64decode
>>> b64encode(b64decode('base64encodedvalue=='))
b'base64encodedvaluQ=='
```

**Comment by kwatsen** [comment]
This is a non-issue.  See https://bugs.python.org/issue42628.
