### ISSUE TITLE
IdentityrefType.from_xml() has issues with prefixed identities

### ISSUE THREAD

**Issue by kwatsen** [CZ-NIC/yangson#76]
When using SchemaNode.from_xml() with a data model and data having a prefixed identity, Yangson throws the error:
```
E           yangson.exceptions.MissingModuleNamespace: <unprintable MissingModuleNamespace object>                                             
```

I have a partial fix, that covers just the case when the prefix is the same as the default namespace, but this issue should stay open until non-default namespace prefixed identities are tested.

**Comment by llhotka** [comment]
Does it work with JSON?

**Comment by kwatsen** [comment]
Yes, a JSON-equivalent test works fine, prefix and all.

I recall seeing a message once from @HRogge regarding an issue with supporting 'xmlns' attributes for prefixed data items.  I'm guessing that this was the very code he was referring to then.

BTW, here's my "fix" mentioned in the OP.

```
--- a/yangson/datatype.py
+++ b/yangson/datatype.py
@@ -681,7 +681,7 @@ class IdentityrefType(DataType):
             i1, s, i2 = xml.text.partition(":")
         except AttributeError:
             return None
-        if not i1:
+        if not i1 or i1 == self.sctx.default_ns:
             return (i2, self.sctx.default_ns)
```

**Comment by kwatsen** [comment]
Closing this issue as #81 is merged and also because using yangson.XMLParser helps.

There is likely still an issue related to the use of a prefix that is NOT the default namespace though...
