### ISSUE TITLE
Identities not imported with conformance-type import

### ISSUE THREAD

**Issue by christian-herber** [CZ-NIC/yangson#84]
According to RFC 7895:
>Indicates that the server imports reusable definitions
>from the specified revision of the module but does
>not implement any protocol-accessible objects from
>this revision."

Imho, an identity is a reusable definition and thus it should be imported. E.g. iana-if-types.yang should usually be "import" and not "implement", but I currently only have these available with the latter.

**Comment by llhotka** [comment]
But [Sec. 9.10.2](https://tools.ietf.org/html/rfc7950#section-9.10.2) in RFC 7950 says:

> On a particular server, the valid values are further restricted to the set of identities defined in the modules implemented by the server.

That's why I think identities from import-only modules aren't available. @kwatsen, any opinion on this?

**Comment by kwatsen** [comment]
I agree with Lada's interpretation.

It's not just the config/opstate data nodes that get "implemented".

**Comment by christian-herber** [comment]
Agree to the comments. YANG 1.1 is clear. The definition in YANG library is ambiguous but the implemented behavior should be correct
