### ISSUE TITLE
Structured Value initialization missing default value

### ISSUE THREAD

**Issue by christian-herber** [CZ-NIC/yangson#89]
When creating a new StructuredValue, documentation suggests there is a default of none for the timestamp:

`classyangson.instvalue.StructuredValue(ts: datetime.datetime = None)`

In the code, the init function lacks this default:

`def __init__(self, ts: datetime):`

ArrayInstance on the other hand has None as default for datetime

`def __init__(self, val: List[EntryValue] = [], ts: datetime = None):`

**Comment by llhotka** [comment]
`StructuredValue` is an abstract class. An instance has to be created as either an `ArrayValue` or `ObjectValue`, and in these two classes the default is set to `None`.
